name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 142.93.175.150
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            /var/www/Pocker/deploy.sh
